[package]
name = "ezwordle2"
license = "MIT"
description = "New and improved Wordle engine."
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wordle"
path = "src/main.rs"

[dependencies]
indicatif = "0.17.8"
